name: zeek-buildah-push-ghcr

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  repository_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/zeek

jobs:
  buildah:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      -
        name: Cancel previous run in progress
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        id: build-base-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          context: .
          containerfiles: |
            ./base.Dockerfile
      -
        name: Push
        id: push-base-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-base-image.outputs.image }}
          tags: ${{ steps.build-base-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
      -
        name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      -
        name: Build plus
        id: build-plus-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: plus
          context: .
          containerfiles: |
            ./plus.Dockerfile
      -
        name: Push plus
        id: push-plus-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-plus-image.outputs.image }}
          tags: ${{ steps.build-plus-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
