---
name: zeek-build-push-ghcr

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:

  build-base-image:
    name: Call Docker Build for base
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./base.Dockerfile
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/zeek
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64

  build-plus-image:
    name: Call Docker Build for plus
    needs: build-base-image
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: .
      file: ./plus.Dockerfile
      cancel-previous-runs: false
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/zeek
      tag-rules: |
        type=raw,value=plus,enable={{is_default_branch}}
        type=raw,value=stable-plus-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
      platforms: linux/amd64

